services:
  - type: web
    name: LTresultmanager
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn LTResultManager.wsgi"
    pythonVersion: 3.11.9
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
    staticPublishPath: staticfiles
