services:
  - type: web
    name: LTresultmanager
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: LTResultManager.settings
