# Generated by Django 4.2.4 on 2025-04-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('grade', models.CharField(choices=[('US', 'US'), ('IGCSE_1', 'IGCSE 1'), ('IGCSE_2', 'IGCSE 2'), ('AS_1', 'AS Level 1'), ('AS_2', 'AS Level 2'), ('GED', 'GED')], max_length=10)),
            ],
        ),
    ]
