# Generated by Django 4.2.4 on 2025-04-11 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_subjects_teacher_subjects_teacher_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subjects',
            new_name='Subject',
        ),
    ]
