# Generated by Django 4.2.4 on 2025-06-22 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSubjectGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('total_marks', models.PositiveIntegerField(default=100)),
                ('marks_obtained', models.PositiveIntegerField()),
                ('grade', models.CharField(max_length=2)),
                ('remarks', models.CharField(max_length=100)),
                ('class_average', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TermReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(default='Term 2', max_length=20)),
                ('days_absent', models.PositiveIntegerField(default=0)),
                ('total_marks', models.PositiveIntegerField(blank=True, null=True)),
                ('marks_obtained', models.PositiveIntegerField(blank=True, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('overall_grade', models.CharField(blank=True, max_length=2)),
                ('comment', models.TextField()),
                ('class_teacher_signature', models.CharField(blank=True, max_length=100)),
                ('academic_head_signature', models.CharField(blank=True, max_length=100)),
                ('head_of_school_signature', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_reports', to='main.student')),
            ],
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.AddField(
            model_name='reportsubjectgrade',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_grades', to='main.termreport'),
        ),
    ]
