# Generated by Django 4.2.4 on 2025-06-22 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_reportsubjectgrade_termreport_delete_report_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termreport',
            name='academic_head_signature',
        ),
        migrations.RemoveField(
            model_name='termreport',
            name='class_teacher_signature',
        ),
        migrations.RemoveField(
            model_name='termreport',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='termreport',
            name='head_of_school_signature',
        ),
        migrations.RemoveField(
            model_name='termreport',
            name='marks_obtained',
        ),
        migrations.RemoveField(
            model_name='termreport',
            name='overall_grade',
        ),
        migrations.RemoveField(
            model_name='termreport',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='termreport',
            name='total_marks',
        ),
        migrations.AddField(
            model_name='reportsubjectgrade',
            name='percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportsubjectgrade',
            name='class_average',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportsubjectgrade',
            name='grade',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='reportsubjectgrade',
            name='remarks',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='reportsubjectgrade',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='main.termreport'),
        ),
        migrations.AlterField(
            model_name='reportsubjectgrade',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subject'),
        ),
        migrations.AlterField(
            model_name='reportsubjectgrade',
            name='total_marks',
            field=models.PositiveIntegerField(),
        ),
    ]
