# Generated by Django 4.2.4 on 2025-06-22 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_reportsubjectgrade_total_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportsubjectgrade',
            name='percentage',
        ),
        migrations.AddField(
            model_name='termreport',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='termreport',
            name='final_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportsubjectgrade',
            name='class_average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportsubjectgrade',
            name='marks_obtained',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='reportsubjectgrade',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_grades', to='main.termreport'),
        ),
    ]
