# Generated by Django 4.2.4 on 2025-06-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_reportsubjectgrade_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termreport',
            name='final_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
