# Generated by Django 4.2.4 on 2025-06-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_termreport_final_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='termreport',
            name='overall_grade',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='termreport',
            name='total_marks_obtained',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
