# Generated by Django 4.2.4 on 2025-06-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_termreport_overall_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsubjectgrade',
            name='class_average',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportsubjectgrade',
            name='marks_obtained',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='reportsubjectgrade',
            name='remarks',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='reportsubjectgrade',
            name='total_marks',
            field=models.PositiveIntegerField(),
        ),
    ]
