# Generated by Django 4.2.4 on 2025-06-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_reportsubjectgrade_marks_obtained_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsubjectgrade',
            name='total_marks',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
