# Generated by Django 4.2.4 on 2025-06-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_reportsubjectgrade_total_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(choices=[('Grade 7', 'Grade 7'), ('Grade 8', 'Grade 8'), ('IGCSE', 'IGCSE'), ('AS', 'AS'), ('GED', 'GED')], max_length=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='grade',
            field=models.CharField(choices=[('Grade 7', 'Grade 7'), ('Grade 8', 'Grade 8'), ('IGCSE', 'IGCSE'), ('AS', 'AS'), ('GED', 'GED')], max_length=10),
        ),
    ]
