# Generated by Django 4.2.4 on 2025-07-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_subject_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
